#!/usr/bin/env python3
import logging
import os
import sys
import time

PROG_NAME = os.path.basename(__file__)

logging.basicConfig(
    level=logging.INFO,
)

token = os.environ.get('SAKURACLOUD_ACCESS_TOKEN')
secret = os.environ.get('SAKURACLOUD_ACCESS_TOKEN_SECRET')
if token is None or secret is None:
    logging.error("Please set both of SAKURACLOUD_ACCESS_TOKEN and SAKURACLOUD_ACCESS_TOKEN_SECRET environment variables")
    sys.exit(2)

logging.info(f"{PROG_NAME} using token={token}")

for i in range(5):
    logging.info(f"fake lego running")
    time.sleep(1)

logging.info(f"fake lego finshed")
